version: "3"

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883
