version: "3"

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883

  db:
    container_name: db
    image: couchdb
    restart: unless-stopped
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: ${DB_PASS}
    volumes:
      - ./db:/opt/couchdb/data

  api:
    container_name: api
    build: "."
    restart: unless-stopped
    depends_on:
      - db
      - mosquitto
    ports:
      - 8000:8000
