version: "3"

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883

  db:
    container_name: db
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "reports"
      MYSQL_USER: "${DB_USER}}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
